name: Notify Discord

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Metadata
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        id: pr_meta
        with:
          script: |
            core.setOutput('title', context.payload.pull_request.title || '')
            core.setOutput('body', context.payload.pull_request.body || '')
            core.setOutput('url', context.payload.pull_request.html_url || '')

      - name: Get Release Metadata
        if: github.event_name == 'release'
        uses: actions/github-script@v6
        id: release_meta
        with:
          script: |
            core.setOutput('title', context.payload.release.name || context.payload.release.tag_name || '')
            core.setOutput('body', context.payload.release.body || '')
            core.setOutput('url', context.payload.release.html_url || '')

      - name: Send Discord Message
        uses: ./.github/actions/discord-webhook
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          pr-title: ${{ steps.pr_meta.outputs.title }}${{ steps.release_meta.outputs.title }}
          pr-body: ${{ steps.pr_meta.outputs.body }}${{ steps.release_meta.outputs.body }}
          pr-url: ${{ steps.pr_meta.outputs.url }}${{ steps.release_meta.outputs.url }}
